spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

file:
  storage:
    path:
      workplace: C:\workplace\
#      user: C:\userSeulmae\
      user: C:\\Users\\hany\\uploads\\users\\

  endPoint:
    workplace: /api/workplace/v1/file